# Exclude a variety of commonly ignored directories.
exclude = [
    ".env",
    ".git",
    ".github",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "venv",
]

[lint]
select = ["E", "W", "F"]
ignore = ["E501", "F401"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
