name: Deploy Flask App to AWS Lambda

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Python version for AWS Lambda

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install zip commmand
        uses: montudor/action-zip@v1

      - name: Create deployment package
        run: |
          mkdir deployment
          pip install --target ./deployment -r requirements.txt
          cp app.py ./deployment/
          cd ./deployment
          zip -r ../flask_lambda.zip .

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:189474657107:function:flask_lambda \
            --zip-file fileb://flask_lambda.zip \
            --region $AWS_REGION
